Repository mainmatter/build-start-rebuild-perf, pull requests merged in 2025-08, with the labels that each got.

#8 Improve README
  README.md
Labels: documentation

#12 fix pnpm workspace
  pnpm-workspace.yaml
Labels: bug

#21 Show stack on error.
  bin/cli.js
Labels: enhancement

#23 Configurable timeout
  lib/program.js
  lib/server.js
  lib/utils.js
Labels: enhancement

#26 The logLevel param is logLevel, not level
  bin/cli.js
Labels: bug

#31 Add shoutout to Discorse for providing inspiration for this tool
  README.md
Labels: documentation

#41 add option to have a custom page-load-timeout
  README.md
  lib/browser.js
  lib/measure.js
  lib/program.js
  test/cli.test.js
Labels: enhancement

#43 use standard puppeteer
  .github/workflows/test.yml
  lib/browser.js
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: enhancement
